AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  AWS CloudFormation ELB Multizone WEB

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'false'
      EnableDnsHostnames: 'false'
      InstanceTenancy: default
      Tags:
        - Key: foo
          Value: bar
