AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  AWS CloudFormation ELB Multizone WEB

Resources:

# Création du VPC

  MainVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: "MainVPC"

# Subnet Public Zone A
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "eu-west-3a"
      CidrBlock:  10.0.0.0/24
      VpcId:
        Ref: MainVPC
      Tags:
        - Key: Name
          Value:  "Subnet-A"

# Subnet Public Zone A
  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "eu-west-3a"
      CidrBlock:  10.0.1.0/24
      VpcId:
        Ref: MainVPC
      Tags:
        - Key: Name
          Value:  "Subnet-A"

