AWSTemplateFormatVersion: 2010-09-09
Description: >-

Parameters:

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  VPNAddress:
    Type: String
    Description: IP Address of your VPN device
    MinLength: '7'
    MaxLength: '15'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: must be a valid IP address of the form x.x.x.x

Resources:
  MonVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: Mon VPC

  MaVpcCustomerGateway:
    Type: 'AWS::EC2::CustomerGateway'
    Properties:
      BgpAsn: 65000
      IpAddress: Internet facing IP of the customer gateway
      Tags:
        - Key: Name
          Value: Ma Customer Gateway
      Type: ipsec.1
