AWSTemplateFormatVersion: "2010-09-09"


Description: >-

Parameters:

  NetworkStackName:
    Description: >-
      Nom de la stack précédente
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: TestVPC

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:
  InstanceIntranet:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum -y update
          sudo amazon-linux-extras install docker
          sudo service docker start
          sudo systemctl enable docker
          sudo usermod -a -G docker ec2-user
          sudo docker run -tid --restart always -p 80:80 --name web nginx:latest
      InstanceType: t2.micro
      ImageId: ami-00798d7180f25aac2
      KeyName: !Ref KeyName
      SubnetId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-SubnetCID'
      PrivateIpAddress: 10.0.2.10
      SecurityGroupIds:
        - !ImportValue
          'Fn::Sub': '${NetworkStackName}-SecurityGroupID'
