# TODO: aws cloudformation deploy --template-file 2_Intranet.yaml --stack-name intranet --parameter-overrides KeyName=tp-terraform NetworkStackName=Network
# TODO : ssh -i "/Users/francisocr/Downloads/tp-terraform.pem" ec2-user@

AWSTemplateFormatVersion: "2010-09-09"


Description: >-

Parameters:

  NetworkStackName:
    Description: >-
      Nom de la stack précédente
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: Network

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:
  InstanceIntranet:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum -y update
          sudo amazon-linux-extras install docker
          sudo service docker start
          sudo systemctl enable docker
          sudo usermod -a -G docker ec2-user
          sudo docker run -tid --restart always -p 80:80 --name web gerbildock/intranet:V1.1
          /opt/aws/bin/cfn-signal -e 0 --resource InstanceIntranet --stack ${AWS::StackName} --region ${AWS::Region}

      InstanceType: t2.micro
      ImageId: ami-00798d7180f25aac2
      KeyName: !Ref KeyName
      SubnetId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-PrivateSubnetC'
      PrivateIpAddress: 10.0.100.10
      SecurityGroupIds:
        - !ImportValue
          'Fn::Sub': '${NetworkStackName}-DMZSg'

    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT5M
