AWSTemplateFormatVersion: "2010-09-09"

Description: >-

Parameters:

  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  NetworkStackName:
    Description: Nom de la Stack reseau
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: network

Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access and HTTP from the load balancer only
      VpcId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-VPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
#          SourceSecurityGroupOwnerId: !ImportValue
#            'Fn::Sub': '${NetworkStackName}-ELB-NSG'
#          SourceSecurityGroupName: !ImportValue
#            'Fn::Sub': '${NetworkStackName}-ELB-OSG'

Outputs:

  InstanceSG:
    Description: Groupe de sécurité pour LaunchConfig
    Value: !Ref InstanceSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-InstanceSG

